/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IacHeader {
    /**
    * Total users online
    */
    'onlineUsersCount': number;
    /**
    * The user profile object
    */
    'userProfile': any;
  }
}

declare global {


  interface HTMLIacHeaderElement extends Components.IacHeader, HTMLStencilElement {}
  var HTMLIacHeaderElement: {
    prototype: HTMLIacHeaderElement;
    new (): HTMLIacHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'iac-header': HTMLIacHeaderElement;
  }
}

declare namespace LocalJSX {
  interface IacHeader extends JSXBase.HTMLAttributes<HTMLIacHeaderElement> {
    /**
    * Total users online
    */
    'onlineUsersCount'?: number;
    /**
    * The user profile object
    */
    'userProfile'?: any;
  }

  interface IntrinsicElements {
    'iac-header': IacHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


